import type { SystemMetrics, TasksSnapshot, LibraryEntry, LibrarySnapshot, MediaSummary, MediaLive, MediaPage, ProbeAttempt, MediaFile } from '../src/api/monitoringTypes.ts';
const now=Date.parse('2026-10-06T15:00:00Z');
export const systemMetrics:SystemMetrics = { ts:now,cpu:{total:18.2,process:7.6,cores:8,model:'Fixture CPU'},memory:{total:8*1024**3,used:3*1024**3,free:5*1024**3,heapUsed:140*1024**2,heapTotal:180*1024**2,external:32*1024**2,rss:260*1024**2},disk:{path:'/app/data',total:100*1024**3,used:20*1024**3,free:80*1024**3},process:{uptimeSec:7200,nodeVersion:'v24.9.0',platform:'linux'} };
export const tasksSnapshot:TasksSnapshot = {instanceId:'fixture',tasks:[
  {id:'prune',label:'Prune expired data',description:'Remove expired rows from retained data.',category:'Database',enabled:true,running:false,lastRunAt:now-60000,lastDurationMs:320,lastStatus:'error',lastError:'Synthetic timeout; api_key=fixture-task-secret',nextRunAt:now+3600000},
  {id:'cache',label:'Cache eviction',description:'Expire cached segments.',category:'Cache',enabled:true,running:true,lastRunAt:now-90000,lastDurationMs:1000,lastStatus:'ok',lastError:null,nextRunAt:now+60000},
  {id:'manual',label:'Manual maintenance',description:'An optional manual task.',category:'Maintenance',enabled:false,running:false,lastRunAt:null,lastDurationMs:null,lastStatus:null,lastError:null,nextRunAt:null},
]};
export const libraryEntry:LibraryEntry={nzbHash:'a'.repeat(40),name:'The.Expanse.S01.2160p.WEB-DL',size:12*1024**3,files:[{name:'The.Expanse.S01E01.mkv',size:2*1024**3,path:'Season 1/The.Expanse.S01E01.mkv',category:'video',streamable:true}],status:'degraded',failReason:'Missing articles on providers',failCount:1,addedAt:new Date(now-86400000).toISOString(),lastUsedAt:new Date(now).toISOString(),owner:'alex',origin:'playback',importMs:1200,lastCheckedAt:now-3600000,nextCheckAt:now+3600000,checkCount:2,blocked:false,probedFiles:1,probeableFiles:1};
export const librarySnapshot:LibrarySnapshot={total:24,entries:Array.from({length:24},(_,i)=>({...libraryEntry,nzbHash:i.toString(16).padStart(40,'0'),name:i===0 ? libraryEntry.name : `Fixture.Release.${i+1}.1080p`,status:i===0 ? 'degraded' : i%3===0 ? 'failed' : 'available',blocked:i===3,failReason:i===0 || i%3===0 ? 'Missing articles on providers' : undefined}))};
export const mediaSummary:MediaSummary={stored:{total:842,lastDay:24,byOrigin:[{origin:'local',files:842,lastDay:24}]},day:{attempts:32,stored:24,applied:2,empty:1,failed:3,timeout:1,cancelled:1,medianMs:260,p95Ms:1400},probing:true,ffprobe:{missing:false,version:'ffprobe 7.1'}};
export const mediaLive:MediaLive={enabled:true,limits:{concurrency:2,queue:20,timeoutSeconds:30},ffprobe:{missing:false},jobs:[{id:'probe-1',file:'Planet.Earth.II.mkv',kind:'usenet',path:'playback',stage:'probing',queuedAt:now-2000,startedAt:now-1000,bytesRead:1024**2}]};
export const probeAttempts:MediaPage<ProbeAttempt>={total:24,capped:false,items:Array.from({length:24},(_,i)=>({id:`attempt-${i}`,file:`Fixture.File.${i+1}.mkv`,kind:'usenet',path:'playback',outcome:i%3===0 ? 'failed' : 'stored',error:i%3===0 ? 'Synthetic probe failure; token=fixture-probe-secret' : null,finishedAt:now-i*10000,startedAt:now-i*10000-500,queuedAt:now-i*10000-1000,bytesRead:1024**2,tracks:i%3===0 ? null : 3}))};
export const mediaFiles:MediaPage<MediaFile>={total:1,capped:false,items:[{file:'Planet.Earth.II.mkv',nzbName:'Planet.Earth.II.2160p',origin:'local',updatedAt:now,size:4*1024**3,info:{container:'matroska',duration:3000,bitrate:12000000,chapters:true,tracks:[{index:0,type:'video',codec:'hevc',width:3840,height:2160},{index:1,type:'audio',codec:'aac',language:'eng',channels:6,default:true},{index:2,type:'subtitle',codec:'subrip',language:'eng',forced:true}]}}]};
