import { useState } from 'react';
import type { UsenetStatsOverview, UsenetWindow } from '../api/types';
import type { Resource } from '../hooks/useData';
import { percent, count, date } from '../lib/format';
import { Badge, Empty, Facts, Status } from '../components/UI';
export function Indexers({ resource, window, setWindow, loginUrl, selected }: { resource:Resource<UsenetStatsOverview>; window:UsenetWindow; setWindow:(w:UsenetWindow)=>void; loginUrl:string; selected?:string }) {
  const [sort,setSort]=useState<'grabs'|'successRate'|'failed'>('grabs');
  const indexers=resource.data?.indexers.filter(i=>selected === undefined || i.indexer === selected).sort((a,b)=>sort==='successRate' ? a.successRate-b.successRate || b.grabs-a.grabs : b[sort]-a[sort] || a.indexer.localeCompare(b.indexer));
  return <><div className="intro"><h1>Indexers</h1><p>Grab outcomes and import health.</p></div>{selected !== undefined && <div className="notice"><div>Showing {selected || "unavailable indexer"}</div><a className="text-button" href="#indexers">Show all indexers</a></div>}<div className="segmented">{(['24h','7d','30d','all'] as const).map(w=><button key={w} aria-pressed={w===window} onClick={()=>setWindow(w)}>{w.toUpperCase()}</button>)}</div><label className="sort-control">Sort indexers<select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="grabs">Most grabs</option><option value="successRate">Lowest success rate</option><option value="failed">Most failures</option></select></label><Status resource={resource} loginUrl={loginUrl}/><div className="stack">{indexers?.map(i=><div className="card indexer-card" key={i.indexer}><div className="provider-heading"><h3>{i.indexer}</h3><Badge state={i.grabs && i.failed===0 ? 'online' : i.failed ? 'paused' : ''}>{i.grabs ? `${percent(i.successRate)} success` : 'No grabs'}</Badge></div><div className="indexer-grid"><div><strong>{count(i.grabs)}</strong><small>Grabs</small></div><div><strong className={i.failed ? 'orange' : ''}>{count(i.failed)}</strong><small>Failed</small></div><div><strong>{count(i.degraded)}</strong><small>Degraded</small></div><div><strong>{count(i.failedMissing)}</strong><small>Missing failures</small></div></div>{(i.fetchAuth>0 || i.fetchLimited>0) && <div className="indexer-warnings">{i.fetchAuth>0 && <span>{count(i.fetchAuth)} auth failures</span>}{i.fetchLimited>0 && <span>{count(i.fetchLimited)} rate limited</span>}</div>}{i.lastError && <div className="indexer-error"><span className="orange">Last error · {date(i.lastError.atMs)}</span><p>{i.lastError.message}</p></div>}<details><summary>More statistics</summary><Facts items={[
    ['OK',count(i.ok)],['Fetch failures',count(i.failedFetch)],['Auth failures',count(i.fetchAuth)],['Rate limited',count(i.fetchLimited)],['Grab share',percent(i.grabShare)],['Average grab',i.avgGrabMs===null ? '—' : `${i.avgGrabMs.toFixed(0)} ms`],['Average import',i.avgImportMs===null ? '—' : `${i.avgImportMs.toFixed(0)} ms`],
  ]}/></details></div>)}{resource.data && !indexers?.length && <Empty title={selected !== undefined ? "Indexer unavailable" : "No indexer activity"}>{selected !== undefined ? "No statistics for this indexer in the selected window. Try another window or show all indexers." : "Stats appear after NZB grabs in this window."}</Empty>}</div><p className="caption">Success includes OK and degraded imports. Rates reflect the selected window.</p></>;
}
