import { useEffect, useState } from 'react';
import type { MediaSummary, MediaLive, MediaPage, ProbeAttempt, MediaFile } from '../api/monitoringTypes';
import { useData } from '../hooks/useData';
import type { Settings } from '../lib/settings';
import { bytes, count, date, duration } from '../lib/format';
import { Status, Empty, Section, Facts, Badge } from '../components/UI';
import { Pagination } from '../components/Pagination';
export function MediaInfo({ settings, loginUrl }: { settings:Settings;loginUrl:string }) {
  const [tab,setTab]=useState<'probes'|'files'>('probes');
  const [search,setSearch]=useState('');
  const [query,setQuery]=useState('');
  const [outcome,setOutcome]=useState('');
  const [offset,setOffset]=useState(0);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setOffset(0);},500);return()=>clearTimeout(timer);},[search]);
  const summary=useData<MediaSummary>(settings.baseUrl,'/media-info',settings.historySeconds,true,false,1,true);
  const supported=!!summary.data && ![401,403,404].includes(summary.error?.status ?? 0);
  const live=useData<MediaLive>(settings.baseUrl,'/media-info/live',settings.pollingSeconds,supported,true,1);
  const params=new URLSearchParams({limit:'20',offset:String(offset)});if(query)params.set('q',query);if(tab==='probes' && outcome)params.set('outcome',outcome);
  const probes=useData<MediaPage<ProbeAttempt>>(settings.baseUrl,`/media-info/probes?${params}`,settings.historySeconds,supported && tab==='probes');
  const files=useData<MediaPage<MediaFile>>(settings.baseUrl,`/media-info/files?${params}`,settings.historySeconds,supported && tab==='files');
  const m=summary.data;
  const page=tab==='probes' ? probes : files;
  return <><div className="intro"><h1>Media info</h1><p>Probe activity, recorded outcomes, and stored tracks.</p></div>{summary.error?.status===404 ? <Empty title="Media Info is unavailable">This AIOStreams version does not expose the Media Info dashboard. Update the instance to use this view.<button onClick={summary.refresh}>Check again</button></Empty> : <Status resource={summary} loginUrl={loginUrl}/>}{m && <><div className="card media-summary"><Facts items={[
    ['Stored files',count(m.stored.total)],['Added in last day',count(m.stored.lastDay)],['Attempts in last 24h',count(m.day.attempts)],['Failed / timed out',`${count(m.day.failed)} / ${count(m.day.timeout)}`],['Median probe time',m.day.medianMs===null ? '—' : `${m.day.medianMs.toLocaleString()} ms`],['Probing',m.probing ? 'Enabled' : 'Disabled'],['ffprobe',m.ffprobe.missing ? 'Unavailable' : m.ffprobe.version || 'Available'],
  ]}/><details className="secondary-facts"><summary>More outcomes &amp; sources</summary><Facts items={[
    ['Stored in last 24h',count(m.day.stored)],['Applied without storage',count(m.day.applied)],['No metadata found',count(m.day.empty)],['Cancelled',count(m.day.cancelled)],['95th percentile',m.day.p95Ms===null ? '—' : `${m.day.p95Ms.toLocaleString()} ms`],...m.stored.byOrigin.map(o=>[o.origin,`${count(o.files)} files`] as [string,string]),
  ]}/></details></div><Section title="Probe queue"><Status resource={live} loginUrl={loginUrl}/>{live.data && <><p className="caption">{live.data.jobs.filter(j=>j.stage==='opening' || j.stage==='probing').length} running · {live.data.jobs.filter(j=>j.stage==='waiting' || j.stage==='queued').length} waiting · {live.data.limits.concurrency} concurrent limit</p>{live.data.jobs.length ? <div className="card probe-queue">{live.data.jobs.slice(0,50).map(job=><div className="probe-row" key={job.id}><strong>{job.file || 'Unnamed file'}</strong><span>{job.stage} · {job.kind} · {bytes(job.bytesRead)} read</span></div>)}{live.data.jobs.length>50 && <p>Showing the first 50 jobs.</p>}</div> : <Empty title="No probes in progress">{live.data.enabled ? 'The queue is quiet.' : 'Probing is disabled on this instance.'}</Empty>}</>}</Section><Section title="Recorded metadata"><div className="segmented"><button aria-pressed={tab==='probes'} onClick={()=>{setTab('probes');setOffset(0);}}>Probe history</button><button aria-pressed={tab==='files'} onClick={()=>{setTab('files');setOffset(0);}}>Stored files</button></div><div className="filters"><label>Search media info<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filename…"/></label>{tab==='probes' && <label>Probe outcome<select value={outcome} onChange={e=>{setOutcome(e.target.value);setOffset(0);}}><option value="">All outcomes</option>{['stored','applied','empty','failed','timeout','cancelled'].map(value=><option key={value} value={value}>{value}</option>)}</select></label>}</div><Status<MediaPage<ProbeAttempt | MediaFile>> resource={page} loginUrl={loginUrl}/><div className="stack">{tab==='probes' ? probes.data?.items.map(attempt=><article className="card probe-entry" key={attempt.id}><h2>{attempt.file || 'Unnamed file'}</h2><Badge state={attempt.outcome==='failed' || attempt.outcome==='timeout' ? 'auth_failed' : attempt.outcome==='stored' || attempt.outcome==='applied' ? 'online' : ''}>{attempt.outcome}</Badge><p>{date(attempt.finishedAt)} · {attempt.kind} · {attempt.path}</p>{attempt.error && <p className="orange">{attempt.error}</p>}<details className="secondary-facts"><summary>Probe details</summary><Facts items={[
    ['Bytes read',bytes(attempt.bytesRead)],['Tracks',attempt.tracks===null ? '—' : count(attempt.tracks)],['Read duration',attempt.startedAt===null ? '—' : duration(attempt.finishedAt-attempt.startedAt)],['Queued',date(attempt.queuedAt)],
  ]}/></details></article>) : files.data?.items.map((file,index)=><article className="card media-file" key={`${file.origin}:${index}`}><h2>{file.nzbName || file.title || file.file || 'Unnamed file'}</h2><p>{file.file}</p><small>{file.origin} · {date(file.updatedAt)}</small><details className="secondary-facts"><summary>Metadata &amp; tracks ({file.info.tracks.length})</summary><Facts items={[
    ['Container',file.info.container || '—'],['Size',file.size===null ? '—' : bytes(file.size)],['Duration',file.info.duration===undefined ? '—' : duration(file.info.duration*1000)],['Bitrate',file.info.bitrate===undefined ? '—' : `${(file.info.bitrate/1000000).toFixed(2)} Mbps`],['Chapters',file.info.chapters ? 'Yes' : 'No'],
  ]}/><ul className="media-tracks">{file.info.tracks.map(track=><li key={track.index}><strong>{track.type} {track.index} · {track.codec || 'Unknown codec'}</strong><small>{[track.language,track.title,track.width && track.height ? `${track.width} × ${track.height}` : '',track.channels ? `${track.channels} channels` : '',track.default ? 'Default' : '',track.forced ? 'Forced' : '',track.hearingImpaired ? 'Hearing impaired' : ''].filter(Boolean).join(' · ') || 'No additional track details'}</small></li>)}</ul>{!file.info.tracks.length && <p>No tracks stored.</p>}</details></article>)}{page.data && !page.data.items.length && <Empty title={tab==='files' ? 'No stored files match' : 'No probe attempts match'}>Try another filter or wait for AIOStreams to record activity.</Empty>}</div><Pagination offset={offset} total={page.data?.total ?? 0} capped={page.data?.capped} busy={page.loading || !!page.refreshing} change={setOffset}/></Section><p className="caption">Read-only monitoring. Opening this view does not start or cancel probes. Totals and history refresh periodically.</p></>}</>;
}
