import type { LiveStats, UsenetStatsOverview, UsenetWindow } from '../api/types';
import type { Resource } from '../hooks/useData';
import { providerHealth } from '../lib/health';
import { speed, count, percent, bytes } from '../lib/format';
import { Badge, Empty, Metric, Section, Status, Facts } from '../components/UI';
import { Chart } from '../components/Chart';
import { Icon } from '../components/Icon';
import { UsenetHistory } from '../components/UsenetHistory';
import { usenetWindowLabel } from '../lib/usage';
export function Usenet({ resource, stats, window, changeWindow, loginUrl, open }: { resource:Resource<LiveStats>; stats:Resource<UsenetStatsOverview>; window:UsenetWindow; changeWindow:(window:UsenetWindow)=>void; loginUrl:string; open:(id:string)=>void }) {
  const live = resource.data?.live;
  const pool = resource.data?.pool;
  const cache = resource.data?.cache;
  const historicalProviders = stats.data?.providers.filter(row => row.removed || (pool && !resource.error && !pool.providers.some(provider => provider.id === row.id))) ?? [];
  return <><div className="intro"><h1>Usenet</h1><p>Throughput, capacity, and provider health.</p><a className="text-button" href="#library">Browse library →</a></div><Status resource={resource} loginUrl={loginUrl}/><div className="metrics usenet-metrics"><Metric label="Current speed" value={speed(live?.currentBytesPerSec)} icon="download" tone="green"/><Metric label="Peak speed" value={speed(live?.peakBytesPerSec)} icon="activity"/><Metric label="Articles / min" value={count(live?.articlesLastMinute)} icon="indexers"/><Metric label="Errors / min" value={count(live?.errorsLastMinute)} icon="activity" tone={live?.errorsLastMinute ? 'orange' : 'green'}/></div>{live && !live.activeStreams && !live.currentBytesPerSec && <p className="caption">No Usenet activity · waiting for playback.</p>}<Section title="Live throughput" action={<span className="muted">{count(live?.activeStreams)} active streams</span>}><div className="card chart-card"><Chart points={resource.samples.map(s => ({at:s.at,value:s.value.live.currentBytesPerSec}))} label="Provider throughput" rate color="green"/><div className="chart-footer">{bytes(live?.bytesLastMinute)} fetched in the last minute</div></div></Section><Section title="Capacity & cache"><div className="card usenet-capacity"><Facts items={[
    ['Fetches on the wire',count(pool?.globalDownloadsOnWire)],['Download capacity',pool && Number.isFinite(pool.globalDownloadsInUse) && Number.isFinite(pool.globalDownloadMax) ? `${count(pool.globalDownloadsInUse)} / ${pool.globalDownloadMax ? count(pool.globalDownloadMax) : 'Unlimited'}` : '—'],['Waiting for capacity',count(pool?.globalDownloadsWaiting)],['Segment cache hit rate',cache && cache.hits+cache.misses>0 ? percent(cache.hitRate) : cache ? 'No requests yet' : '—'],['Disk cache size',bytes(cache?.diskBytes)],
  ]}/><details className="secondary-facts"><summary>Cache details</summary><Facts items={[
    ['Cache hits',count(cache?.hits)],['Cache misses',count(cache?.misses)],['Disk cache entries',count(cache?.diskCount)],['Disk cache hits',count(cache?.diskHits)],
  ]}/></details><p className="caption">Capacity includes work not yet transferring. Waiting fetches do not necessarily mean playback is stalled.</p></div></Section><UsenetHistory stats={stats} window={window} change={changeWindow} loginUrl={loginUrl}/><Section title="Provider connections" action={<span className="muted">{resource.data?.pool.providers.length ?? '—'} providers</span>}><p className="caption">Missing and error rates: {usenetWindowLabel(window).toLowerCase()}.</p><div className="stack">{resource.data?.pool.providers.map(p => { const stat=stats.data?.providers.find(s=>s.id===p.id); const health=providerHealth(p,stat); return <button className="card provider-card" key={p.id} onClick={()=>open(p.id)}><div className="provider-heading"><div><h3>{p.name || stat?.name || stat?.host || p.id}</h3><Badge state={health.state}>{health.label}</Badge>{p.isBackup && <Badge>Backup</Badge>}</div><Icon name="arrow" size={18}/></div><div className="provider-metrics"><div><strong>{p.acquired}<span> / {p.max}</span></strong><small>Connections in use</small></div><div><strong>{speed(p.throughput)}</strong><small>{health.state==='idle' ? 'Last sampled speed' : 'Current throughput'}</small></div></div><div className="progress green"><div style={{width:`${p.max ? Math.min(100,p.acquired/p.max*100) : 0}%`}}/></div><div className="provider-foot"><span>Missing {percent(stat?.missRate)}</span><span>Errors {percent(stat?.errorRate)}</span><span>{p.idle} idle</span></div>{health.warnings.map(w=><p key={w} className="orange">{w}</p>)}</button>; })}{resource.data && !resource.data.pool.providers.length && <Empty title="No providers in the pool">Configured provider connections will appear here.</Empty>}</div></Section>{historicalProviders.length > 0 && <Section title="Recorded provider history"><div className="stack">{historicalProviders.map(row => <button className="card provider-card" key={row.id} onClick={()=>open(row.id)}><div className="provider-heading"><div><h3>{row.name || row.host || row.id}</h3><Badge>{row.removed ? 'Removed provider' : 'Not in live pool'}</Badge></div><Icon name="arrow" size={18}/></div><p>{bytes(row.bytes)} fetched · {count(row.errors)} errors · {usenetWindowLabel(window).toLowerCase()}</p></button>)}</div><p className="caption">Recorded activity remains after a provider leaves the pool. It does not indicate current provider health.</p></Section>}</>;
}
